name: marketplace-release

on:
  workflow_run:
    workflows: [ test ]
    types:
      - completed

jobs:
  publish-idea-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: 'Release IDEA'
        env:
          MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
        run: ./gradlew publishPlugin
