name: marketplace-release

on: [ workflow_dispatch ]

jobs:
  publish-idea-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: 'Release IDEA'
        env:
          MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
        run: ./gradlew publishPlugin
